# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = '$os$all $status$line_break$character'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
symbol = "\U000f0320 "

[os]
disabled = false

[os.symbols]
Debian = "\ue77d "
Macos = "\ue711 "
Ubuntu = "\uef72 "

[status]
disabled = false
symbol = "\uf467 "
sigint_symbol = "\ue009"

[hostname]
ssh_symbol = "@"
format = '[$ssh_symbol$hostname]($style) '

[username]
format = '[$user]($style)'
